# Reducing angular derivative
gains:
  #pos: {x: 1.5, y: 1.5, z: 1.7}
  #vel: {x: 0.0, y: 0.7, z: 0.7}
  pos: {x: 1.2, y: 1.0, z: 5.8}
  vel: {x: 0.7, y: 0.5, z: 0.7}
  rot: {x: 1.5, y: 1.5, z: 1.0}
  ang: {x: 0.13, y: 0.13, z: 0.1}
  ki:  {x: 0.00, y: 0.00, z: 0.008}
  pos: {x: 1.2, y: 0.7, z: 1.8}
  vel: {x: 0.7, y: 0.2, z: 0.7}
  rot: {x: 1.5, y: 1.5, z: 1.0}
  ang: {x: 0.13, y: 0.13, z: 0.1}
  ki:  {x: 0.00, y: 0.000, z: 0.008}
corrections:
  kf: 0.0
  r: 0.0
  p: 0.0

