# Reducing angular derivative
gains:
#  pos: {x: 4.0105, y: 4.0105, z: 6.6842}
#  vel: {x: 1.3368, y: 1.3368, z: 3.7877}
  pos: {x: 1.8, y: 1.6, z: 3.0}
  vel: {x: 0.6, y: 0.5, z: 1.5}
  rot: {x: 0.6, y: 0.25, z: 0.07}
  ang: {x: 0.1, y: 0.02, z: 0.007}
  ki:  {x: 0.00, y: 0.00, z: 0.0}
Inertia:
  I: {Ix: 0.0207, Ixy: 0.0, Ixz: 0.0, Iyx: 0.0, Iy: 0.0012, Iyz: 0.0, Izx: 0.0, Izy: 0.0, Iz:  0.0217}
kf: 0.000000004179
kM_kf: 0.0095
arm_length: 0.07071067811
corrections:
  kf: 0.0
  r: 0.0
  p: 0.0
vehicle_id: 0
